ALTER TABLE pets
ADD COLUMN thirst INT NOT NULL DEFAULT 100;

ALTER TABLE pets
ADD COLUMN thirst_last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE pets
ADD COLUMN social INT NOT NULL DEFAULT 100;

ALTER TABLE pets
ADD COLUMN social_last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE pets
ADD COLUMN fun INT NOT NULL DEFAULT 100;

ALTER TABLE pets
ADD COLUMN fun_last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;